substitutions: # set up unique values for this hardware instance
  id_prefix: sprinkler


esphome:
  name: sprinkler
  friendly_name: sprinkler

esp32:
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:


web_server:

ota:
  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sprinkler Fallback Hotspot"
    password: "12345"

captive_portal:

sprinkler:
  - id: ${id_prefix}_sprinklers
    main_switch: "Sprinklers"
    auto_advance_switch: "Sprinklers Auto Advance"
    valves:
      - valve_switch: "Zona 1"
        enable_switch: "Enable Zona 1"
        run_duration_number:
          id: zone_1_run_duration
          name: "Zone 1 Run Duration"
          icon: "mdi:timer-outline"
          initial_value: 1
          unit_of_measurement: min
        valve_switch_id: lawn_sprinkler_valve_sw1
      - valve_switch: "Zona 2"
        enable_switch: "Enable Zona 2"
        run_duration_number:
          id: zone_2_run_duration
          name: "Zone 2 Run Duration"
          icon: "mdi:timer-outline"
          initial_value: 1
          unit_of_measurement: min
        valve_switch_id: lawn_sprinkler_valve_sw2
      - valve_switch: "Zona 3"
        enable_switch: "Enable Zona 3"
        run_duration_number:
          id: zone_3_run_duration
          name: "Zone 3 Run Duration"
          icon: "mdi:timer-outline"
          initial_value: 1
          unit_of_measurement: min
        valve_switch_id: lawn_sprinkler_valve_sw3
      - valve_switch: "Zona 4"
        enable_switch: "Enable Zona 4"
        run_duration_number:
          id: zone_4_run_duration
          name: "Zone 4 Run Duration"
          icon: "mdi:timer-outline"
          initial_value: 1
          unit_of_measurement: min
        valve_switch_id: lawn_sprinkler_valve_sw4
      - valve_switch: "Zona 5"
        enable_switch: "Enable Zona 5"
        run_duration_number: 
          id: zone_5_run_duration
          name: "Zone 5 Run Duration"
          icon: "mdi:timer-outline"
          initial_value: 1
          unit_of_measurement: min
        valve_switch_id: lawn_sprinkler_valve_sw5
      - valve_switch: "Zona 6"
        enable_switch: "Enable Zona 6"
        run_duration_number:
          id: zone_6_run_duration
          name: "Zone 6 Run Duration"
          icon: "mdi:timer-outline"
          initial_value: 1
          unit_of_measurement: min
        valve_switch_id: lawn_sprinkler_valve_sw6
      - valve_switch: "Zona 7"
        enable_switch: "Enable Zona 7"
        run_duration_number:
          id: zone_7_run_duration
          name: "Zone 7 Run Duration"
          icon: "mdi:timer-outline"
          initial_value: 1
          unit_of_measurement: min
        valve_switch_id: lawn_sprinkler_valve_sw7
      - valve_switch: "Zona 8"
        enable_switch: "Enable Zona 8"
        run_duration_number:
          id: zone_8_run_duration
          name: "Zone 8 Run Duration"
          icon: "mdi:timer-outline"
          initial_value: 1
          unit_of_measurement: min
        valve_switch_id: lawn_sprinkler_valve_sw8


switch:
  - platform: gpio
    id: lawn_sprinkler_valve_sw1
    pin: GPIO19
  - platform: gpio
    id: lawn_sprinkler_valve_sw2
    pin: GPIO18
  - platform: gpio
    id: lawn_sprinkler_valve_sw3
    pin: GPIO17
  - platform: gpio
    id: lawn_sprinkler_valve_sw4
    pin: GPIO16  
  - platform: gpio
    id: lawn_sprinkler_valve_sw5
    pin: GPIO32
  - platform: gpio
    id: lawn_sprinkler_valve_sw6
    pin: GPIO33
  - platform: gpio
    id: lawn_sprinkler_valve_sw7
    pin: GPIO25
  - platform: gpio
    id: lawn_sprinkler_valve_sw8
    pin: GPIO26
    # day of week toggle switches
  - platform: template
    id: ${id_prefix}_sunday
    name:  Sunday
    icon: "mdi:calendar-range"
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
  - platform: template
    id: ${id_prefix}_monday
    name:  Monday
    icon: "mdi:calendar-range"
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
  - platform: template
    id: ${id_prefix}_tuesday
    name:  Tuesday
    icon: "mdi:calendar-range"
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
  - platform: template
    id: ${id_prefix}_wednesday
    name:  Wednesday
    icon: "mdi:calendar-range"
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
  - platform: template
    id: ${id_prefix}_thursday
    name:  Thursday
    icon: "mdi:calendar-range"
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
  - platform: template
    id: ${id_prefix}_friday
    name:  Friday
    icon: "mdi:calendar-range"
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
  - platform: template
    id: ${id_prefix}_saturday
    name:  Saturday
    icon: "mdi:calendar-range"
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
  # scheduled time enable switches
  - platform: template
    id: ${id_prefix}_schedule1_enabled
    name: Enable Schedule 1
    icon: "mdi:clock-outline"
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
  - platform: template
    id: ${id_prefix}_schedule2_enabled
    name: Enable Schedule 2
    icon: "mdi:clock-outline"
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
  - platform: template
    id: ${id_prefix}_schedule3_enabled
    name: Enable Schedule 3
    icon: "mdi:clock-outline"
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
  # rain delay switches (can be cancelled, auto-resetting)
  - platform: template
    id: ${id_prefix}_raindelay_24h_enabled
    name: Enable 24h Rain Delay
    icon: "mdi:weather-cloudy-clock"
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    turn_on_action:
      then:
        - delay: 
            hours: 24
        - switch.turn_off: ${id_prefix}_raindelay_24h_enabled
  - platform: template
    id: ${id_prefix}_raindelay_48h_enabled
    name: Enable 48h Rain Delay
    icon: "mdi:weather-cloudy-clock"
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    turn_on_action:
      then:
        - delay: 
            hours: 48
        - switch.turn_off: ${id_prefix}_raindelay_48h_enabled


datetime:
  - platform: template
    name: Schedule 1 Start Time
    entity_category: config
    id: ${id_prefix}_s1t
    type: time
    optimistic: true
    restore_value: true
  - platform: template
    name: Schedule 2 Start Time
    entity_category: config
    id: ${id_prefix}_s2t
    type: time
    optimistic: true
    restore_value: true
  - platform: template
    name: Schedule 3 Start Time
    entity_category: config
    id: ${id_prefix}_s3t
    type: time
    optimistic: true
    restore_value: true

# set up time and check every minute (or second) for scheduled actions
time:
  - platform: homeassistant
    id: ha_time
    on_time:
      # Every 1 minute
      - seconds: 0
        minutes: /1
        then:
          - script.execute: ${id_prefix}_script1
    on_time_sync:
      then:
        - logger.log: "Synchronized system clock"

script:
    # check what day of the week it is currently, and if we have the schedule enabled today
    - id: ${id_prefix}_script1 
      then:
        lambda: |-
          int dow = id(ha_time).now().day_of_week;
          if      ((dow == 1 && id(${id_prefix}_sunday).state == true)
          ||       (dow == 2 && id(${id_prefix}_monday).state == true)
          ||       (dow == 3 && id(${id_prefix}_tuesday).state == true)
          ||       (dow == 4 && id(${id_prefix}_wednesday).state == true)
          ||       (dow == 5 && id(${id_prefix}_thursday).state == true)
          ||       (dow == 6 && id(${id_prefix}_friday).state == true)
          ||       (dow == 7 && id(${id_prefix}_saturday).state == true)) {
            id(${id_prefix}_script2).execute();
          }
    # if current time is equal to any of the scheduled start times, start the sprinkler cycle
    - id: ${id_prefix}_script2
      then:
        lambda: |-
          int hour = id(ha_time).now().hour;
          int minute = id(ha_time).now().minute;
          if      ((hour == id(${id_prefix}_s1t).hour && minute == id(${id_prefix}_s1t).minute && id(${id_prefix}_schedule1_enabled).state == true && id(${id_prefix}_raindelay_24h_enabled).state == false && id(${id_prefix}_raindelay_48h_enabled).state == false)
          ||      (hour == id(${id_prefix}_s2t).hour && minute == id(${id_prefix}_s2t).minute && id(${id_prefix}_schedule2_enabled).state == true && id(${id_prefix}_raindelay_24h_enabled).state == false && id(${id_prefix}_raindelay_48h_enabled).state == false)
          ||      (hour == id(${id_prefix}_s3t).hour && minute == id(${id_prefix}_s3t).minute && id(${id_prefix}_schedule3_enabled).state == true && id(${id_prefix}_raindelay_24h_enabled).state == false && id(${id_prefix}_raindelay_48h_enabled).state == false)) {
            id(${id_prefix}_script3).execute();
          }
    # start the sprinkler cycle
    - id: ${id_prefix}_script3
      then:
        - sprinkler.start_full_cycle: ${id_prefix}_sprinklers
        - lambda: ESP_LOGI("main", "Sprinkler cycle has begun!");

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
  - platform: uptime
    name: Uptime
    entity_category: "diagnostic"

binary_sensor:
  - platform: status
    name: "Connection Status"